version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: testuser
      DB_PASS: testpass
      DB_NAME: testdb
      DB_SSL_MODE: disable  # Set to disable for testing

    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
